name: omniedge build

on:
  workflow_dispatch:
  schedule:
    - cron: 0 */24 * * *
jobs:
  build-freebsd-binary:
    runs-on: macos-12
    env:
      ENVIRONMENT: prod
    name: Build on FreeBSD
    steps:
      - name: Checkout with tag
        uses: actions/checkout@master
        
      - uses: actions/checkout@v2
      - name: prepare
        id: test
        uses: vmactions/freebsd-vm@v0.1.8
        with:
          usesh: true
          run: |
            pkg update
            free -h
            pkg install -y bash go gmake git openssl zip autoconf automake libtool
            chsh -s bash
            make generate
            BUILD_ENV=${{ env.ENVIRONMENT }} make build-freebsd
            zip -j ./omniedge-${{ github.ref_name }}-freebsd-13.1.zip ./out/omniedge
      
      - name: Archive package
        uses: actions/upload-artifact@v2
        with:
          path: omniedge-${{ github.ref_name }}-freebsd-13.1.zip
          name: omniedge-${{ github.ref_name }}-freebsd-13.1.zip
          if-no-files-found: error
          
      - name: Upload package to GitHub Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file_glob: true
          overwrite: true
          file: omniedge-${{ github.ref_name }}-freebsd-13.1.zip
