name: release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: tag ( if tag is not empty, env is always prod)
        required: false

jobs:
  relase:
    name: release omniedge cli
    env:
      TAG: ${{ github.event.inputs.tag }}
    runs-on: ubuntu-latest
    steps:
      - name: Invoke amd64 build workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: amd64-build
          token: ${{ secrets.GIT_HUB_TOKEN }}
          inputs: '{"envName":"prod","tag":"${{env.TAG}}","invokeDeploy":"true"}'
      - name: Invoke arm64v8 build workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: arm64v8-build
          token: ${{ secrets.GIT_HUB_TOKEN }}
          inputs: '{"envName":"prod","tag":"${{env.TAG}}","invokeDeploy":"true"}'

      - name: Invoke armv7 build workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: armv7-build
          token: ${{ secrets.GIT_HUB_TOKEN }}
          inputs: '{"envName":"prod","tag":"${{env.TAG}}","invokeDeploy":"true"}'
      - name: Invoke darwin build workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: darwin-build
          token: ${{ secrets.GIT_HUB_TOKEN }}
          inputs: '{"envName":"prod","tag":"${{env.TAG}}","invokeDeploy":"true"}'

      - name: Invoke ppc64le build workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: ppc64le-build
          token: ${{ secrets.GIT_HUB_TOKEN }}
          inputs: '{"envName":"prod","tag":"${{env.TAG}}","invokeDeploy":"true"}'